export const LISTING_LIST_REQUEST = "LISTING_LIST_REQUEST";
export const LISTING_LIST_SUCCESS = "LISTING_LIST_SUCCESS";
export const LISTING_LIST_FAIL = "LISTING_LIST_FAIL";
export const LISTING_ADD = "LISTING_ADD";
export const LISTING_UPDATE = "LISTING_UPDATE";
export const LISTING_DELETE = "LISTING_DELETE";